# Header
menu:
  文章: /
  归档: /archives
  关于: /about/index.html
rss: 
github: https://github.com/wensonsmith

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- archive
- recent_posts
- tagcloud
- links

# Links
links: 
  Hexo: http://hexo.io

# Miscellaneous
google_analytics: UA-51369930-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
